<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>En16931</PackageId>
    <Version>0.1.0</Version>
    <Authors>Jonas Fassbender</Authors>
    <Company>fassbender.dev</Company>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Transient dependency of SaxonCS-HE; added here to avoid vulnerability warnings -->
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="SaxonCS-HE" Version="13.0.0" />
    <!-- Transient dependency of SaxonCS-HE; added here to avoid vulnerability warnings -->
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\En16931.Resources.Extern\**\*.*">
      <PackagePath>contentFiles/any/any/En16931.Resources.Extern</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackageFlatten>false</PackageFlatten>
    </Content>
    <Content Include="..\IR\**\*.*">
      <PackagePath>contentFiles/any/any/IR</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackageFlatten>false</PackageFlatten>
    </Content>
  </ItemGroup>

</Project>
