<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Tests</PackageId>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\En16931\En16931.csproj" />
  </ItemGroup>

  <Target Name="CopyResources" AfterTargets="Build">
    <ItemGroup>
      <TestResources Include="..\Tests.Resources\**\*.*" />
      <ExternTestResources Include="..\Tests.Resources.Extern\**\*.*" />
      <ExternResources Include="..\En16931.Resources.Extern\**\*.*" />
      <IRResources Include="..\IR\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TestResources)" DestinationFolder="$(OutDir)\Tests.Resources\%(RecursiveDir)" />
    <Copy SourceFiles="@(ExternTestResources)" DestinationFolder="$(OutDir)\Tests.Resources.Extern\%(RecursiveDir)" />
    <Copy SourceFiles="@(ExternResources)" DestinationFolder="$(OutDir)\En16931.Resources.Extern\%(RecursiveDir)" />
    <Copy SourceFiles="@(IRResources)" DestinationFolder="$(OutDir)\IR\%(RecursiveDir)" />
  </Target>

</Project>
