using System;
using En16931.Model.Primitives;
using En16931.Model.XRechnungExtension;
using M = En16931.Model;
using S = En16931.Specs;

namespace Tests.XRechnungExtension.Invoices;

public partial class UblInvoices
{
    public static readonly Invoice Invoice3 = new Invoice
    {
        InvoiceNumber = new Identifier("12345"),
        InvoiceIssueDate = new Date(new DateTime(2019, 5, 15)),
        InvoiceTypeCode = new Code("380"),
        InvoiceCurrencyCode = new Code("EUR"),
        VatAccountingCurrencyCode = null,
        ValueAddedTaxPointDate = null,
        ValueAddedTaxPointDateCode = null,
        PaymentDueDate = null,
        BuyerReference = new Text("12345678-12345-83"),
        ProjectReference = null,
        ContractReference = null,
        PurchaseOrderReference = new DocumentReference("123"),
        SalesOrderReference = null,
        ReceivingAdviceReference = null,
        DespatchAdviceReference = null,
        TenderOrLotReference = null,
        InvoicedObjectIdentifier = null,
        BuyerAccountingReference = null,
        PaymentTerms = new Text("Zahlbar innerhalb 14 Tagen nach Erhalt der Rechnung."),
        InvoiceNotes = [],
        ProcessControl = new M.ProcessControl<S.XRechnungExtension>
        {
            BusinessProcessType = new Text("urn:fdc:peppol.eu:2017:poacc:billing:01:1.0"),
        },
        PrecedingInvoiceReferences = [],
        Seller = new M.Seller
        {
            SellerName = new Text("M. Meier Handwerk GbR"),
            SellerTradingName = new Text("M. Meier"),
            SellerIdentifiers = [],
            SellerLegalRegistrationIdentifier = new Identifier("1122334455"),
            SellerVatIdentifier = new Identifier("DE/12/345/67890"),
            SellerTaxRegistrationIdentifier = null,
            SellerAdditionalLegalInformation = null,
            SellerElectronicAddress = new Identifier("seller@email.de", "EM"),
            SellerPostalAddress = new M.SellerPostalAddress
            {
                SellerAddressLine1 = new Text("Hauptstraße 2"),
                SellerAddressLine2 = null,
                SellerAddressLine3 = null,
                SellerCity = new Text("Musterstadt"),
                SellerPostCode = new Text("12345"),
                SellerCountrySubdivision = null,
                SellerCountryCode = new Code("DE"),
            },
            SellerContact = new M.SellerContact
            {
                SellerContactPoint = new Text("M. Meier Handwerk GbR"),
                SellerContactTelephoneNumber = new Text("010/12345"),
                SellerContactEmailAddress = new Text("info@m-meier.de"),
            },
        },
        Buyer = new M.Buyer
        {
            BuyerName = new Text("Beispielkunde"),
            BuyerTradingName = null,
            BuyerIdentifier = new Identifier("345LA5324"),
            BuyerLegalRegistrationIdentifier = null,
            BuyerVatIdentifier = null,
            BuyerElectronicAddress = new Identifier("buyer@info.de", "EM"),
            BuyerPostalAddress = new M.BuyerPostalAddress
            {
                BuyerAddressLine1 = new Text("Dorfplatz 3"),
                BuyerAddressLine2 = null,
                BuyerAddressLine3 = null,
                BuyerCity = new Text("Musterort"),
                BuyerPostCode = new Text("54321"),
                BuyerCountrySubdivision = null,
                BuyerCountryCode = new Code("DE"),
            },
            BuyerContact = null,
        },
        Payee = null,
        SellerTaxRepresentativeParty = null,
        DeliveryInformation = new M.DeliveryInformation
        {
            DeliverToPartyName = null,
            DeliverToLocationIdentifier = null,
            ActualDeliveryDate = null,
            InvoicingPeriod = new M.InvoicingPeriod
            {
                InvoicingPeriodStartDate = new Date(new DateTime(2019, 2, 1)),
                InvoicingPeriodEndDate = new Date(new DateTime(2019, 5, 7)),
            },
            DeliverToAddress = null,
        },
        PaymentInstructions = new M.PaymentInstructions
        {
            PaymentMeansTypeCode = new Code("31"),
            PaymentMeansText = null,
            RemittanceInformation = null,
            CreditTransfers = [
                new M.CreditTransfer {
                    PaymentAccountIdentifier = new Identifier("DE091111222233334444"),
                    PaymentAccountName = null,
                    PaymentServiceProviderIdentifier = null,
                },
            ],
            PaymentCardInformation = null,
            DirectDebit = null,
        },
        DocumentLevelAllowances = [],
        DocumentLevelCharges = [],
        DocumentTotals = new M.DocumentTotals
        {
            SumOfInvoiceLineNetAmount = new Amount(12536.84m),
            SumOfAllowancesOnDocumentLevel = null,
            SumOfChargesOnDocumentLevel = null,
            InvoiceTotalAmountWithoutVat = new Amount(12536.84m),
            InvoiceTotalVatAmount = new Amount(2382m),
            InvoiceTotalVatAmountInAccountingCurrency = null,
            InvoiceTotalAmountWithVat = new Amount(14918.84m),
            PaidAmount = new Amount(10000m),
            RoundingAmount = null,
            AmountDueForPayment = new Amount(4918.84m),
        },
        VatBreakdown = [
            new M.VatBreakdown {
                VatCategoryTaxableAmount = new Amount(12536.84m),
                VatCategoryTaxAmount = new Amount(2382m),
                VatCategoryCode = new Code("S"),
                VatCategoryRate = new Percentage(19m),
                VatExemptionReasonText = null,
                VatExemptionReasonCode = null,
            },
        ],
        AdditionalSupportingDocuments = [],
        InvoiceLines = [
            new InvoiceLine {
                InvoiceLineIdentifier = new Identifier("1"),
                InvoiceLineNote = null,
                InvoiceLineObjectIdentifier = null,
                InvoicedQuantity = new Quantity(1m),
                InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                InvoiceLineNetAmount = new Amount(818.04m),
                ReferencedPurchaseOrderLineReference = null,
                InvoiceLineBuyerAccountingReference = null,
                InvoiceLinePeriod = null,
                InvoiceLineAllowances = [],
                InvoiceLineCharges = [],
                PriceDetails = new M.PriceDetails {
                    ItemNetPrice = new UnitPriceAmount(818.04m),
                    ItemPriceDiscount = null,
                    ItemGrossPrice = null,
                    ItemPriceBaseQuantity = new Quantity(1m),
                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                },
                LineVatInformation = new M.LineVatInformation {
                    InvoicedItemVatCategoryCode = new Code("S"),
                    InvoicedItemVatRate = new Percentage(19m),
                },
                ItemInformation = new M.ItemInformation {
                    ItemName = new Text("Sanitär und Zubehör"),
                    ItemDescription = null,
                    ItemSellersIdentifier = null,
                    ItemBuyersIdentifier = null,
                    ItemStandardIdentifier = null,
                    ItemClassificationIdentifiers = [],
                    ItemCountryOfOrigin = null,
                    ItemAttributes = [],
                },
                SubInvoiceLines = [
                    new SubInvoiceLine {
                        InvoiceLineIdentifier = new Identifier("1 1"),
                        InvoiceLineNote = null,
                        InvoiceLineObjectIdentifier = null,
                        InvoicedQuantity = new Quantity(1m),
                        InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                        InvoiceLineNetAmount = new Amount(335.79m),
                        ReferencedPurchaseOrderLineReference = null,
                        InvoiceLineBuyerAccountingReference = null,
                        SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                            ItemName = new Text("Demontage Sanitär"),
                            ItemDescription = null,
                            ItemSellersIdentifier = null,
                            ItemBuyersIdentifier = null,
                            ItemStandardIdentifier = null,
                            ItemClassificationIdentifiers = [],
                            ItemCountryOfOrigin = null,
                            SubInvoiceLineItemAttributes = [],
                        },
                        SubInvoiceLineAllowances = [],
                        SubInvoiceLineCharges = [],
                        SubInvoiceLinePeriod = null,
                        SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                            InvoicedItemVatCategoryCode = new Code("S"),
                            InvoicedItemVatRate = new Percentage(19m),
                        },
                        SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                            ItemNetPrice = new UnitPriceAmount(335.79m),
                            ItemPriceDiscount = null,
                            ItemGrossPrice = null,
                            ItemPriceBaseQuantity = new Quantity(1m),
                            ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                        },
                        SubInvoiceLines = [
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("1 1 1"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(149m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("MTR"),
                                InvoiceLineNetAmount = new Amount(193.70m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Demontage TW-Rohrleitung DN 12-25"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(1.30m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("MTR"),
                                },
                                SubInvoiceLines = [],
                            },
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("1 1 2"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(32.50m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("MTR"),
                                InvoiceLineNetAmount = new Amount(48.75m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Demontage SML DN 100"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(1.50m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("MTR"),
                                },
                                SubInvoiceLines = [],
                            },
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("1 1 3"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(71.80m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("MTR"),
                                InvoiceLineNetAmount = new Amount(93.34m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Demontage AW-Rohrleitungen Kunststoff PP bis DN100"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(1.30m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("MTR"),
                                },
                                SubInvoiceLines = [],
                            },
                        ],
                    },
                    new SubInvoiceLine {
                        InvoiceLineIdentifier = new Identifier("1 2"),
                        InvoiceLineNote = null,
                        InvoiceLineObjectIdentifier = null,
                        InvoicedQuantity = new Quantity(1m),
                        InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                        InvoiceLineNetAmount = new Amount(482.25m),
                        ReferencedPurchaseOrderLineReference = null,
                        InvoiceLineBuyerAccountingReference = null,
                        SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                            ItemName = new Text("Abwasserleitungen und Zubehör"),
                            ItemDescription = null,
                            ItemSellersIdentifier = null,
                            ItemBuyersIdentifier = null,
                            ItemStandardIdentifier = null,
                            ItemClassificationIdentifiers = [],
                            ItemCountryOfOrigin = null,
                            SubInvoiceLineItemAttributes = [],
                        },
                        SubInvoiceLineAllowances = [],
                        SubInvoiceLineCharges = [],
                        SubInvoiceLinePeriod = null,
                        SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                            InvoicedItemVatCategoryCode = new Code("S"),
                            InvoicedItemVatRate = new Percentage(19m),
                        },
                        SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                            ItemNetPrice = new UnitPriceAmount(482.25m),
                            ItemPriceDiscount = null,
                            ItemGrossPrice = null,
                            ItemPriceBaseQuantity = new Quantity(1m),
                            ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                        },
                        SubInvoiceLines = [
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("1 2 1"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(9.5m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("MTR"),
                                InvoiceLineNetAmount = new Amount(99.75m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Abwasserleitung HT-PP DN 100"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(10.50m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("MTR"),
                                },
                                SubInvoiceLines = [],
                            },
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("1 2 2"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(45.0m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("MTR"),
                                InvoiceLineNetAmount = new Amount(382.50m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Abwasserleitung HT-PP DN 50"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(8.50m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("MTR"),
                                },
                                SubInvoiceLines = [],
                            },
                        ],
                    }
                ],
            },
            new InvoiceLine {
                InvoiceLineIdentifier = new Identifier("2"),
                InvoiceLineNote = null,
                InvoiceLineObjectIdentifier = null,
                InvoicedQuantity = new Quantity(1m),
                InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                InvoiceLineNetAmount = new Amount(11718.8m),
                ReferencedPurchaseOrderLineReference = null,
                InvoiceLineBuyerAccountingReference = null,
                InvoiceLinePeriod = null,
                InvoiceLineAllowances = [],
                InvoiceLineCharges = [],
                PriceDetails = new M.PriceDetails {
                    ItemNetPrice = new UnitPriceAmount(11718.8m),
                    ItemPriceDiscount = null,
                    ItemGrossPrice = null,
                    ItemPriceBaseQuantity = new Quantity(1m),
                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                },
                LineVatInformation = new M.LineVatInformation {
                    InvoicedItemVatCategoryCode = new Code("S"),
                    InvoicedItemVatRate = new Percentage(19m),
                },
                ItemInformation = new M.ItemInformation {
                    ItemName = new Text("Heizung und Zubehör"),
                    ItemDescription = null,
                    ItemSellersIdentifier = null,
                    ItemBuyersIdentifier = null,
                    ItemStandardIdentifier = null,
                    ItemClassificationIdentifiers = [],
                    ItemCountryOfOrigin = null,
                    ItemAttributes = [],
                },
                SubInvoiceLines = [
                    new SubInvoiceLine {
                        InvoiceLineIdentifier = new Identifier("2 1"),
                        InvoiceLineNote = null,
                        InvoiceLineObjectIdentifier = null,
                        InvoicedQuantity = new Quantity(1m),
                        InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                        InvoiceLineNetAmount = new Amount(1324m),
                        ReferencedPurchaseOrderLineReference = null,
                        InvoiceLineBuyerAccountingReference = null,
                        SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                            ItemName = new Text("Demontage Heizung"),
                            ItemDescription = null,
                            ItemSellersIdentifier = null,
                            ItemBuyersIdentifier = null,
                            ItemStandardIdentifier = null,
                            ItemClassificationIdentifiers = [],
                            ItemCountryOfOrigin = null,
                            SubInvoiceLineItemAttributes = [],
                        },
                        SubInvoiceLineAllowances = [],
                        SubInvoiceLineCharges = [],
                        SubInvoiceLinePeriod = null,
                        SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                            InvoicedItemVatCategoryCode = new Code("S"),
                            InvoicedItemVatRate = new Percentage(19m),
                        },
                        SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                            ItemNetPrice = new UnitPriceAmount(1324m),
                            ItemPriceDiscount = null,
                            ItemGrossPrice = null,
                            ItemPriceBaseQuantity = new Quantity(1m),
                            ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                        },
                        SubInvoiceLines = [
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("2 1 1"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(20m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("C62"),
                                InvoiceLineNetAmount = new Amount(700m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Entleeren der Heizungsanlage, teilnetz"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(35m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("C62"),
                                },
                                SubInvoiceLines = [],
                            },
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("2 1 2"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(52m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("C62"),
                                InvoiceLineNetAmount = new Amount(624m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Demontage Flachheizkörpers"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(12m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("C62"),
                                },
                                SubInvoiceLines = [],
                            },
                        ],
                    },
                    new SubInvoiceLine {
                        InvoiceLineIdentifier = new Identifier("2 2"),
                        InvoiceLineNote = null,
                        InvoiceLineObjectIdentifier = null,
                        InvoicedQuantity = new Quantity(1m),
                        InvoicedQuantityUnitOfMeasureCode = new Code("XPP"),
                        InvoiceLineNetAmount = new Amount(10394.8m),
                        ReferencedPurchaseOrderLineReference = null,
                        InvoiceLineBuyerAccountingReference = null,
                        SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                            ItemName = new Text("Heizflächen und Zubehör"),
                            ItemDescription = null,
                            ItemSellersIdentifier = null,
                            ItemBuyersIdentifier = null,
                            ItemStandardIdentifier = null,
                            ItemClassificationIdentifiers = [],
                            ItemCountryOfOrigin = null,
                            SubInvoiceLineItemAttributes = [],
                        },
                        SubInvoiceLineAllowances = [],
                        SubInvoiceLineCharges = [],
                        SubInvoiceLinePeriod = null,
                        SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                            InvoicedItemVatCategoryCode = new Code("S"),
                            InvoicedItemVatRate = new Percentage(19m),
                        },
                        SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                            ItemNetPrice = new UnitPriceAmount(10394.8m),
                            ItemPriceDiscount = null,
                            ItemGrossPrice = null,
                            ItemPriceBaseQuantity = new Quantity(1m),
                            ItemPriceBaseQuantityUnitOfMeasureCode = new Code("XPP"),
                        },
                        SubInvoiceLines = [
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("2 2 1"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(52m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("C62"),
                                InvoiceLineNetAmount = new Amount(10202.4m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Flachheizkörper Stahl profiliert Seitent. H 300mm L -500mm Typ22"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(196.20m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("C62"),
                                },
                                SubInvoiceLines = [],
                            },
                            new SubInvoiceLine {
                                InvoiceLineIdentifier = new Identifier("2 2 2"),
                                InvoiceLineNote = null,
                                InvoiceLineObjectIdentifier = null,
                                InvoicedQuantity = new Quantity(104m),
                                InvoicedQuantityUnitOfMeasureCode = new Code("C62"),
                                InvoiceLineNetAmount = new Amount(192.4m),
                                ReferencedPurchaseOrderLineReference = null,
                                InvoiceLineBuyerAccountingReference = null,
                                SubInvoiceLineItemInformation = new SubInvoiceLineItemInformation {
                                    ItemName = new Text("Einzelrosette aus Kunststoff, weiß"),
                                    ItemDescription = null,
                                    ItemSellersIdentifier = null,
                                    ItemBuyersIdentifier = null,
                                    ItemStandardIdentifier = null,
                                    ItemClassificationIdentifiers = [],
                                    ItemCountryOfOrigin = null,
                                    SubInvoiceLineItemAttributes = [],
                                },
                                SubInvoiceLineAllowances = [],
                                SubInvoiceLineCharges = [],
                                SubInvoiceLinePeriod = null,
                                SubInvoiceLineVatInformation = new SubInvoiceLineVatInformation {
                                    InvoicedItemVatCategoryCode = new Code("S"),
                                    InvoicedItemVatRate = new Percentage(19m),
                                },
                                SubInvoiceLinePriceDetails = new SubInvoiceLinePriceDetails {
                                    ItemNetPrice = new UnitPriceAmount(1.85m),
                                    ItemPriceDiscount = null,
                                    ItemGrossPrice = null,
                                    ItemPriceBaseQuantity = new Quantity(1m),
                                    ItemPriceBaseQuantityUnitOfMeasureCode = new Code("C62"),
                                },
                                SubInvoiceLines = [],
                            },
                        ],
                    }
                ],
            },
        ],
        ThirdPartyPayments = [],
    };
}
